; Configuration file generated by main.py on 2025-11-11 21:44:47
#Requires AutoHotkey v2.0

; Specific structure variables (Can be expanded if needed)
AHK_ROOT_NAME := "Deepr"

; Configuration structure based on settings.json
class A_Path
{
    static rootDir := A_ScriptDir
    static Configuration := this.rootDir "\.config"
    static SupportFiles := this.rootDir "\SupportFiles"
    static AHK := this.SupportFiles "\AHK"
    static Icons := this.SupportFiles "\Icons"
    static Images := this.SupportFiles "\Images"
    static ImageSearch := this.SupportFiles "\ImageSearch"
    static Pythons := this.SupportFiles "\Pythons"
    static Sounds := this.SupportFiles "\Sounds"
    static Library := this.rootDir "\Library"
    static Core := this.Library "\Core"
    static Classes := this.Core "\Classes"
    static Functions := this.Core "\Functions"
    static GUIs := this.Library "\GUIs"
    static Modules := this.Library "\Modules"
    static Windows := this.Modules "\Windows"
    static PremierePro := this.Modules "\Premiere Pro"
    static AfterFx := this.Modules "\After Effects"

}

; ========================================
; --- AUTO-GENERATED SCRIPT INCLUDES ---
; ========================================

; --- 1. Global Includes (Always Active) ---


; --- Source: Deepr.Library.Core.Classes ---
#include "%A_ScriptDir%\Library\Core\Classes\Core_Settings.ahk"

; --- Source: Deepr.Library.Core.Functions ---
#include "%A_ScriptDir%\Library\Core\Functions\JoinArray.ahk"
#include "%A_ScriptDir%\Library\Core\Functions\Message.ahk"
#include "%A_ScriptDir%\Library\Core\Functions\SearchCaret.ahk"
#include "%A_ScriptDir%\Library\Core\Functions\SendInputControlFocusBack.ahk"
#include "%A_ScriptDir%\Library\Core\Functions\WatchApp.ahk"
#include "%A_ScriptDir%\Library\Core\Functions\WatchError.ahk"
#include "%A_ScriptDir%\Library\Core\Functions\WatchModifierKeys.ahk"
#include "%A_ScriptDir%\Library\Core\Functions\WatchMouse.ahk"
#include "%A_ScriptDir%\Library\Core\Functions\WatchTooltip.ahk"
#include "%A_ScriptDir%\Library\Core\Functions\fileNameConstructor.ahk"

; --- Source: Deepr.Library.GUIs ---
#include "%A_ScriptDir%\Library\GUIs\Debug.ahk"
#include "%A_ScriptDir%\Library\GUIs\SideNote.ahk"
#include "%A_ScriptDir%\Library\GUIs\SuspendScriptGUI.ahk"

; --- Source: Deepr.Library.Modules.Windows ---
#include "%A_ScriptDir%\Library\Modules\Windows\Windows_Hotkeys.ahk"

; --- Source: Deepr.Library.Modules.Windows.Classes ---
#include "%A_ScriptDir%\Library\Modules\Windows\Classes\App_Class.ahk"

; --- Source: Deepr.Library.Modules.Windows.Functions ---
#include "%A_ScriptDir%\Library\Modules\Windows\Functions\AlwaysOnTop.ahk"
#include "%A_ScriptDir%\Library\Modules\Windows\Functions\Application.ahk"
#include "%A_ScriptDir%\Library\Modules\Windows\Functions\ClassNN_toCoords.ahk"
#include "%A_ScriptDir%\Library\Modules\Windows\Functions\ClipCursor.ahk"
#include "%A_ScriptDir%\Library\Modules\Windows\Functions\FindCaret.ahk"
#include "%A_ScriptDir%\Library\Modules\Windows\Functions\HandleKeyGestures.ahk"
#include "%A_ScriptDir%\Library\Modules\Windows\Functions\Komorebic.ahk"
#include "%A_ScriptDir%\Library\Modules\Windows\Functions\Language.ahk"
#include "%A_ScriptDir%\Library\Modules\Windows\Functions\Mouse.ahk"
#include "%A_ScriptDir%\Library\Modules\Windows\Functions\Terminal.ahk"
#include "%A_ScriptDir%\Library\Modules\Windows\Functions\Volume.ahk"
#include "%A_ScriptDir%\Library\Modules\Windows\Functions\WaitForUserConfirm.ahk"
#include "%A_ScriptDir%\Library\Modules\Windows\Functions\Window.ahk"
#include "%A_ScriptDir%\Library\Modules\Windows\Functions\autofill.ahk"

; --- 2. Context-Sensitive (HotIf) Includes ---


; --- Context: ahk_exe Adobe Premiere Pro.exe ---
#HotIf WinActive("ahk_exe Adobe Premiere Pro.exe")

; --- Source: Deepr.Library.Modules.PremierePro ---
#include "%A_ScriptDir%\Library\Modules\Premiere Pro\PremierePro_Hotkeys.ahk"

; --- Source: Deepr.Library.Modules.PremierePro.Classes ---
#include "%A_ScriptDir%\Library\Modules\Premiere Pro\Classes\PremierePro_Attributes.ahk"
#include "%A_ScriptDir%\Library\Modules\Premiere Pro\Classes\PremierePro_Class.ahk"

; --- Source: Deepr.Library.Modules.PremierePro.Functions ---
#include "%A_ScriptDir%\Library\Modules\Premiere Pro\Functions\ApplyPreset.ahk"
#include "%A_ScriptDir%\Library\Modules\Premiere Pro\Functions\ClipClear.ahk"
#include "%A_ScriptDir%\Library\Modules\Premiere Pro\Functions\ClipGain.ahk"
#include "%A_ScriptDir%\Library\Modules\Premiere Pro\Functions\Effects.ahk"
#include "%A_ScriptDir%\Library\Modules\Premiere Pro\Functions\Keyframe.ahk"
#include "%A_ScriptDir%\Library\Modules\Premiere Pro\Functions\Motion.ahk"
#include "%A_ScriptDir%\Library\Modules\Premiere Pro\Functions\Panel.ahk"
#include "%A_ScriptDir%\Library\Modules\Premiere Pro\Functions\Paste.ahk"
#include "%A_ScriptDir%\Library\Modules\Premiere Pro\Functions\Project.ahk"
#include "%A_ScriptDir%\Library\Modules\Premiere Pro\Functions\TrueCtrlBackspace.ahk"
#include "%A_ScriptDir%\Library\Modules\Premiere Pro\Functions\TrueFullscreen.ahk"
#include "%A_ScriptDir%\Library\Modules\Premiere Pro\Functions\ValueEdit.Ahk"
#include "%A_ScriptDir%\Library\Modules\Premiere Pro\Functions\closeWin.ahk"
#HotIf ; End context ahk_exe Adobe Premiere Pro.exe

; --- Context: ahk_exe AfterFX.exe ---
#HotIf WinActive("ahk_exe AfterFX.exe")

; --- Source: Deepr.Library.Modules.AfterFx ---
#include "%A_ScriptDir%\Library\Modules\After Effects\AfterFX_Hotkeys.ahk"

; --- Source: Deepr.Library.Modules.AfterFx.Classes ---
#include "%A_ScriptDir%\Library\Modules\After Effects\Classes\AfterFX_Class.ahk"
#HotIf ; End context ahk_exe AfterFX.exe

#HotIf ; Final context reset